create table users(
                      id number generated by default as identity primary key,
                      username varchar(30) unique not null,
                      password varchar(10) not null
);

create table groups(
                       id number generated by default as identity primary key,
                       name varchar(50) not null,
                       created_by number
);

create table members(
                        user_id number,
                        group_id number,
                        primary key(user_id,group_id)
);

create table resources(
                          id number generated by default as identity primary key,
                          title varchar(50),
                          descr char(100),
                          upload_by number,
                          group_id number,
                          file_data BLOB
);

create table messages(
                         id number generated by default as identity primary key,
                         user_id number not null,
                         group_id number not null,
                         message varchar(255) not null
);